name: class_at
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5
  intl: ^0.18.1
  cupertino_icons: ^1.0.8
  characters: 1.3.0
  collection: 1.19.0
  material_color_utilities: ^0.11.1
  meta: 1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  async: ^2.11.0
  boolean_selector: 2.1.1 # Downgraded to match flutter_test requirement
  clock: 1.1.1
  fake_async: 1.3.1
  leak_tracker: ^10.0.7
  leak_tracker_flutter_testing: 3.0.8
  lints: ^5.1.1
  matcher: 0.12.16+1
  path: ^1.9.0
  source_span: 1.10.0
  stack_trace: ^1.12.0
  stream_channel: 2.1.2
  string_scanner: 1.3.0
  term_glyph: 1.2.1
  test_api: 0.7.3
  vm_service: ^14.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lecturer.jpeg
    - assets/Student.jpeg
    - assets/teaching_assistant.jpeg
    - assets/university_logo.jpeg
